### PR TITLE
Post/Media title, and Term names are all HTML

### PR DESCRIPTION
**Pull request by Mange**
This should make that problem more obvious when using this gem.

@rmeritz what do you think about adding `#name` and `#title` variants that unescape the HTML? We could use Nokogiri for the task.

### CODE REVIEW

**Comment by rmeritz** [comment]
Looks good.

> @rmeritz what do you think about adding #name and #title variants that unescape the HTML? We could use Nokogiri for the task.

You can add them. But I would skip it unless you find anywhere that we actually need it. I think I was pretty care just to skip adding `h` in the templates wherever they are used. It seems weird to add those methods and not add a content that escapes the `content` that escapes the content. (Same for excerpt). Also then we have added dependency on `Nokogiri` that we don't really need.

**Comment by Mange** [comment]
> But I would skip it unless you find anywhere that we actually need it.

Sure. YAGNI and all that. We might use it for comparing values, however. We have a category with `&` in it, so string comparisons do not match.

> I think I was pretty care just to skip adding `h` in the templates wherever they are used.

I want to make it more obvious that the content of the strings should be handled as actual HTML that you need to strip dangerous tags from or trust blindly.

> It seems weird to add those methods and not add a content that escapes the `content` that escapes the content.

What? :confused: 

> Also then we have added dependency on Nokogiri that we don't really need.

Yeah, right. I forgot we didn't use Nokogiri in this gem. There are other more light-weight versions one could use.

**Comment by rmeritz** [comment]
> Sure. YAGNI and all that. We might use it for comparing values, however. We have a category with & in it, so string comparisons do not match.

You love to say `YAGNI`. I say follow your own wisdom. You can use the slug or id for comparison.

**Comment by rmeritz** [comment]
> I want to make it more obvious that the content of the strings should be handled as actual HTML that you need to strip dangerous tags from or trust blindly.

Which is why its it great that you rename these methods as you did in this PR.

**Comment by rmeritz** [comment]
>> It seems weird to add those methods and not add a content that escapes the content that escapes the content.

> What? :confused: 

I mean if you do at a `title` method that escapes the html in `title_html` then you should probably corresponding methods for all the methods ending in `_html`, not just some. But I don't really think you should add them at all.

**Pull request merged**
